package com.example.minesweeper;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Score
 * -----
 * Represents a single game result entry in the Room database.
 * Each record contains:
 *  - Auto-generated ID
 *  - Difficulty level (Easy / Medium / Hard)
 *  - Completion time (in seconds)
 *  - Date and time of completion
 *
 * This entity is stored inside the "scores" table.
 */
@Entity(tableName = "scores")
public class Score {

    /** Primary key ID, automatically generated by Room */
    @PrimaryKey(autoGenerate = true)
    private int id;

    /** The difficulty of the game (e.g., "Easy", "Medium", "Hard") */
    private String difficulty;

    /** Time in seconds the player took to finish the game */
    private int time;

    /** Date and time when the game was completed */
    private String date;

    /** Constructor — used when inserting a new score */
    public Score(String difficulty, int time, String date) {
        this.difficulty = difficulty;
        this.time = time;
        this.date = date;
    }

    // --- Getters and Setters ---
    public int getId() {return id;}
    public String getDifficulty() {return difficulty;}
    public String getDate() {return date;}
    public int getTime() {return time;}

    public void setTime(int time) {this.time = time;}
    public void setId(int id) {this.id = id;}
    public void setDifficulty(String difficulty) {this.difficulty = difficulty;}
    public void setDate(String date) {this.date = date;}
}
